// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKOJ72DalElV_LzqMdDUZw0sO84tzmEYw',
    appId: '1:517686766793:web:9568b829483ac0470e3118',
    messagingSenderId: '517686766793',
    projectId: 'sg-sst-db',
    authDomain: 'sg-sst-db.firebaseapp.com',
    storageBucket: 'sg-sst-db.firebasestorage.app',
    measurementId: 'G-GFKSN97HGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYWtSkMmtbNuv7J1IK4xhjmZcpS2VvQRw',
    appId: '1:517686766793:android:7f0802dd52214fba0e3118',
    messagingSenderId: '517686766793',
    projectId: 'sg-sst-db',
    storageBucket: 'sg-sst-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBicH1J7klj8DTBvGoEWotWPHC4D1FOTQo',
    appId: '1:517686766793:ios:a29de4806a26a9060e3118',
    messagingSenderId: '517686766793',
    projectId: 'sg-sst-db',
    storageBucket: 'sg-sst-db.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBicH1J7klj8DTBvGoEWotWPHC4D1FOTQo',
    appId: '1:517686766793:ios:a29de4806a26a9060e3118',
    messagingSenderId: '517686766793',
    projectId: 'sg-sst-db',
    storageBucket: 'sg-sst-db.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKOJ72DalElV_LzqMdDUZw0sO84tzmEYw',
    appId: '1:517686766793:web:4e85011dcbde9dce0e3118',
    messagingSenderId: '517686766793',
    projectId: 'sg-sst-db',
    authDomain: 'sg-sst-db.firebaseapp.com',
    storageBucket: 'sg-sst-db.firebasestorage.app',
    measurementId: 'G-ZCV5EPK94Q',
  );
}
